
Vagrant.configure(2) do |config|
  config.vm.box = "arch"
  # config.vm.synced_folder "host_path", "guest_path"

  config.vm.define "master" do |master|
  	  master.vm.synced_folder "../sync/master", "/home/vagrant/Desktop/"
      master.vm.hostname = "master.vagrant"
	  master.vm.network "private_network", ip: "192.168.33.10", virtualbox__intnet: "intnet"
	  master.vm.network "private_network", ip: "192.168.33.11", virtualbox__intnet: "intnet"
  end

  # config.vm.define "host1" do |host1|
  # 	  host1.vm.synced_folder "../sync/host1", "/home/vagrant/Desktop/"
  #     host1.vm.hostname = "host1.vagrant"
  #     host1.vm.network "private_network", ip: "192.168.33.111", virtualbox__intnet: "intnet"
  # end

  # config.vm.define "host2" do |host2|
  # 	  host2.vm.synced_folder "../sync/host2", "/home/vagrant/Desktop/"
  #     host2.vm.hostname = "host2.vagrant"
  #     host2.vm.network "private_network", ip: "192.168.33.222", virtualbox__intnet: "intnet"
  # end

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
